--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ItsToxicGG/TheBridge
build-by-default: true
branches:
- main
projects:
  TheBridge:
    path: ""
    libs:
      - src: EasyUI
        version: ^1.0.2
...
